/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Theme-aware — uses CSS variables set by ThemeContext (700ms ease) with fallbacks for SSR
        "surface-dim": "var(--surface, #131315)",
        "canvas-pure-white": "var(--surface-light, #FFFFFF)",
        "secondary-fixed": "var(--surface-light-container, #d3e4ff)",
        "surface-tint": "var(--accent, #abc7ff)",
        surface: "var(--surface, #131315)",
        outline: "var(--border-color, #8b919f)",
        "on-primary": "#fcfbff",
        "on-secondary": "#fcfbff",
        tertiary: "var(--accent, #ffb783)",
        "on-secondary-container": "var(--text-on-dark, #88b8f7)",
        "canvas-dark": "var(--surface-dark, #1D1D1F)",
        "primary-fixed": "var(--surface-light-container, #d7e2ff)",
        "outline-variant": "var(--border-color, #414753)",
        "on-tertiary-container": "var(--text-on-dark, #fffaf9)",
        "surface-container-low": "var(--surface-container, #1b1b1d)",
        "secondary-fixed-dim": "var(--accent, #a2c9ff)",
        "inverse-surface": "var(--text-on-dark, #e4e2e4)",
        "tertiary-fixed": "var(--surface-light-container, #ffdcc5)",
        "tertiary-container": "var(--accent, #a36536)",
        "on-secondary-fixed-variant": "var(--text-on-dark, #054880)",
        "surface-bright": "var(--surface-container-high, #39393b)",
        "on-surface": "var(--text-on-dark, #e4e2e4)",
        "on-surface-variant": "var(--text-secondary-on-dark, #c1c6d6)",
        "on-tertiary-fixed-variant": "var(--text-on-dark, #6d390d)",
        "on-primary-container": "#fcfbff",
        "on-tertiary": "var(--text-on-dark, #4f2500)",
        "on-background": "var(--text-on-dark, #e4e2e4)",
        error: "#ffb4ab",
        "secondary-container": "var(--accent, #054880)",
        "canvas-light-gray": "var(--surface-light-container, #F5F5F7)",
        "surface-container-highest": "var(--surface-container-high, #353437)",
        "primary-container": "var(--accent, #0071e3)",
        "text-secondary-dark": "var(--text-secondary-on-dark, #A1A1A6)",
        "inverse-primary": "var(--accent, #005cbb)",
        "surface-container": "var(--surface-container, #1f1f21)",
        "surface-container-lowest": "var(--surface-dark, #0e0e10)",
        "border-light": "var(--border-light, #E5E5EA)",
        "on-tertiary-fixed": "var(--text-on-dark, #301400)",
        "on-primary-fixed-variant": "var(--accent, #00458f)",
        "surface-container-high": "var(--surface-container-high, #2a2a2c)",
        "tertiary-fixed-dim": "var(--accent, #ffb783)",
        background: "var(--surface, #131315)",
        "text-muted-dark": "var(--text-muted-on-dark, #86868B)",
        "canvas-pure-black": "var(--surface-dark, #000000)",
        "primary-fixed-dim": "var(--accent, #abc7ff)",
        secondary: "var(--accent, #a2c9ff)",
        primary: "var(--accent, #abc7ff)",
        "accent-electric-hover": "var(--accent-hover, #0077ED)",
        "text-muted-light": "var(--text-muted-on-light, #6E6E73)",
        "on-error": "#690005",
        "canvas-card-dark": "var(--surface, #161617)",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-variant": "var(--surface-container, #353437)",
        "on-primary-fixed": "var(--text-on-dark, #001b3f)",
        "on-secondary-fixed": "var(--text-on-dark, #001c38)",
        "inverse-on-surface": "var(--surface, #303032)",
        "border-dark": "var(--border-color, #333336)",
        glass: "rgba(255,255,255,0.15)",
        "glass-strong": "rgba(255,255,255,0.18)",
        "glass-subtle": "rgba(255,255,255,0.08)",
        "glass-border": "rgba(255,255,255,0.2)",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      backdropBlur: {
        30: "30px",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "section-hero": "8rem",
        "gutter-desktop": "2rem",
        "container-max": "75rem",
        "section-tight": "4rem",
        "section-regular": "6rem",
        "margin-mobile": "1.25rem",
        "margin-desktop": "3rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "display-xl": ["Inter"],
        "display-xl-mobile": ["Inter"],
        "title-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "title-lg": ["Inter"],
        "headline-md-mobile": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "label-md": ["JetBrains Mono"],
      },
      fontSize: {
        "headline-lg-mobile": ["34px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["40px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "display-xl": ["80px", { lineHeight: "84px", letterSpacing: "-0.035em", fontWeight: "700" }],
        "display-xl-mobile": ["44px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "title-md": ["19px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["56px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-lg": ["19px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "title-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-md-mobile": ["28px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
